package com.ooml_codegen.compiler.parser.ooml.ast;

public enum NodeType {
    T_CLASS,
    T_INTERFACE,
    T_PACKAGE,
    T_INHERITANCE,
    T_ENUM,
    T_WORD,
    T_QUOTED_WORD,
    T_SINGLE_LINE_COMMENT,
    T_MULTI_LINE_COMMENT,
    T_COLON,
    T_SEMI_COLON,
    T_EQUAL,
    T_SIGN,
    T_ACCESS_MODIFIER_BLOCK,

    R_comment,
    R_word,
    R_Start,
    R_list,
    R_entry,
    R_class,
    R_class_model,
    R_class_prop_list,
    R_class_prop,
    R_restricted_access_modifier,
    R_class_access_block,
    R_class_prop_block_list,
    R_class_prop_block,
    R_attribute_with_access,
    R_attribute,
    R_modifier_list,
    R_modifier,
    R_accessors,
    R_getter,
    R_setter,
    R_method_with_access,
    R_method,
    R_argument_list,
    R_type,
    R_constructor_with_access,
    R_constructor,
    R_interface,
    R_interface_model,
    R_interface_prop_list,
    R_interface_prop,
    R_interface_access_block,
    R_interface_prop_block_list,
    R_interface_prop_block,
    R_package,
    R_inheritance,
    R_inheritance_list,
    R_enum,
    R_enum_model,
    R_enum_value_list,
    R_enum_key;




}
