package com.ooml_codegen.compiler.lexer;

public enum TokenType {

    SINGLE_LINE_COMMENT,
    MULTI_LINE_COMMENT,
    IMPORT,
    PACKAGE,
    CLASS,
    INTERFACE,
    ENUM,
    INHERITANCE,
    ACCESS_MODIFIER,
    COLON,
    EQUAL,
    SIGN,
    WORD,
    COMMA,
    OPENING_PARENTHESIS,
    CLOSING_PARENTHESIS,
    OPENING_BRACKET,
    CLOSING_BRACKET,
    OPENING_CURLY_BRACKET,
    CLOSING_CURLY_BRACKET,
    EOF

}
