name: Run OOML_CodeGen tests

run-name: ${{ github.ref }} is being tested

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Java
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: temurin

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run tests
        run: mvn test --file pom.xml